config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users,
              :path => '', 
              :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
              :controllers => {:registrations => 'registrations' }
  

  root 'pages#home'
  
  resources :users, only: [:show]
  
  resources :rooms do
    resources :reservations, only: [:create]
  end
  resources :photos

  
  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'
  
  get '/your_trips' => 'reservations#your_trips'
  
  get '/your_reservations' => 'reservations#your_reservations' 

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :room
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
    
    # pour faire une réservation il faut être authentifié
    before_action :authenticate_user!
    
    
    def preload
       room = Room.find(params[:room_id])
       today = Date.today
       # date de réservation début et fin plus tard que la date d'aujourd'hui
       reservations = room.reservations.where("start_date >= ? OR end_date >= ?", today, today)
       
       render json: reservations
    end
    
      def preview
        start_date = Date.parse(params[:start_date])
        end_date = Date.parse(params[:end_date])
        output = {
            conflict: is_conflict(start_date, end_date)
        }
        render json: output
    end
    
    # méthode de création d'une réservation par le current user
    # redirection vers la page de réservation
    def create
    @reservation = current_user.reservations.create(reservation_params)       
    redirect_to @reservation.room, notice: "Votre réservation a été acceptée"
    end
    
    def your_trips
       @trips = current_user.reservations 
    end

    def your_reservations
      @rooms = current_user.rooms
    end
  
private
     # on ne met pas user_id car la personne qui réserve est le current_user
     def reservation_params         
        params.require(:reservation).permit(:start_date, :end_date, :price, :total, :room_id)     
     end 
     
     def is_conflict(start_date, end_date)
        room = Room.find(params[:room_id])

        check = room.reservations.where("? < start_date AND end_date < ?", start_date, end_date)
        check.size > 0? true : false
    end
end

app/views/reservations/_form.html.erb
<%= form_for([@room, @room.reservations.new]) do |f| %>

<!-- affichage de prix -->
<div class="row">
        <div class="col-md-12 price_tag">
            <span>€ <%= @room.price %></span>
            <span class="pull-right">Par nuit</span>
        </div>
    </div>
    
<div class="row">

         <div class="col-md-6">

         <label>Arrivée</label>
        <!-- input de date de début -->
         <%= f.text_field :start_date, readonly: 'true', placeholder: 'jj/mm/aaaa', class: 'form-control' %>

         </div>

         <div class="col-md-6">

         <label>Départ</label>
        <!-- input de date de fin -->
        <!-- disabled true : permet de ne pas pouvoir cliquer sur date de fin -->
         <%= f.text_field :end_date, readonly: 'true', placeholder: 'jj/mm/aaaa', class: 'form-control', disabled: 'true' %>

         </div>

 </div>
 
 <!-- Affichage de nuits réservés -->
 <!-- style display none -> Permet d'afficher seulement lorsqu'il y a des informations -->
 <div id="preview" style="display: none">

       <table class="reservation-table" >

               <tbody>

                    <tr>

                        <td>Nuit(s)</td>

                        <td><span id="reservation_days"></span></td>

                    </tr>

                    <tr>

                         <td>Total</td>

                         <td><span id="reservation_sum"></span>€</td>

                   </tr>

               </tbody>

        </table>

 </div>
     <!-- A QUOI SERVENT LES CHAMPS CACHES -->
     <%= f.hidden_field :room_id, value: @room.id %> <!-- champs caché pour renseigner l’id du logement et le prix -->
     <%= f.hidden_field :price, value: @room.price %>
     <%= f.hidden_field :total, id: 'reservation_total' %>
 <br>
     <%= f.submit "Demande de réservation ", class: "btn btn-primary wide" %>
 <% end %>

<!-- script datepicker : https://jqueryui.com/datepicker/ -->
<script>
  function unavailable(date) {
    dmy = date.getDate() + "-" + (date.getMonth() + 1) + "-" + date.getFullYear();
    return [$.inArray(dmy, unavailableDates) == -1];
  }
  $(function () {

    unavailableDates = [];

    $.ajax({
      url: '/preload',
      data: {
        'room_id': <%= @room.id %>
      },
      dataType: 'json',
      success: function (data) {
        $.each(data, function (arrID, arrValue) {
          for (var d = new Date(arrValue.start_date); d <= new Date(arrValue.end_date); d.setDate(d.getDate() + 1)) {
            unavailableDates.push($.datepicker.formatDate('d-m-yy', d));
          }
        })

        $('#reservation_start_date').datepicker({
          dateFormat: 'dd-mm-yy',
          monthNames: [
            'Janvier',
            'Février',
            'Mars',
            'Avril',
            'Mai',
            'Juin',
            'Juillet',
            'Août',
            'Septembre',
            'Octobre',
            'Novembre',
            'Décembre'
          ],
          dayNamesMin: [
            'D',
            'L',
            'M',
            'M',
            'J',
            'V',
            'S'
          ],
          minDate: 0,
          maxDate: '3m',
          beforeShowDay: unavailable,
          onSelect: function (selected) {
            var newdate = new Date($("#reservation_start_date").datepicker("getDate"));
            newdate.setDate(newdate.getDate() + 1);
            $('#reservation_end_date').datepicker("option", "minDate", newdate);
            $('#reservation_end_date').attr('disabled', false);

            var start_date = $(this).datepicker('getDate');
            var end_date = $('#reservation_end_date').datepicker('getDate');
            var diff = (end_date - start_date) / 1000 / 60 / 60 / 24;
            var days = Math.round(diff);

            var input = {
              'start_date': start_date,
              'end_date': end_date,
              'room_id': <%= @room.id %>

            }

            $.ajax({
              url: '/preview',
              data: input,
              success: function (data) {
                if (data.conflict) {
                  $('#message').show();
                  $('#message').text("Ces dates sont indisponibles");
                  $('#preview').hide();
                  $('#btn_book').attr('disabled', true);
                } else {
                  $('#message').hide();
                  $('#preview').show();
                  $('#btn_book').attr('disabled', false);

                  var total = days * <%= @room.price %>
                  $('#reservation_days').text(days);
                  $('#reservation_sum').text(total);
                  $('#reservation_total').val(total);
                }

              }
            });

          }
        });

        $('#reservation_end_date').datepicker({
          dateFormat: 'dd-mm-yy',
          monthNames: [
            'Janvier',
            'Février',
            'Mars',
            'Avril',
            'Mai',
            'Juin',
            'Juillet',
            'Août',
            'Septembre',
            'Octobre',
            'Novembre',
            'Décembre'
          ],
          dayNamesMin: [
            'D',
            'L',
            'M',
            'M',
            'J',
            'V',
            'S'
          ],
          minDate: 0,
          maxDate: '3m',
          beforeShowDay: unavailable,
          onSelect: function (selected) {
            $('#reservation_start_date').datepicker("option", "maxDate", selected);

            var start_date = $('#reservation_start_date').datepicker('getDate');
            var end_date = $(this).datepicker('getDate');
            var diff = (end_date - start_date) / 1000 / 60 / 60 / 24;
            var days = Math.round(diff);

            var input = {
              'start_date': start_date,
              'end_date': end_date,
              'room_id': <%= @room.id %>

            }

            $.ajax({
              url: '/preview',
              data: input,
              success: function (data) {
                if (data.conflict) {
                  $('#message').show();
                  $('#message').text("Ces dates sont indisponibles");
                  $('#preview').hide();
                  $('#btn_book').attr('disabled', true);
                } else {
                  $('#message').hide();
                  $('#preview').show();
                  $('#btn_book').attr('disabled', false);

                  var total = days * <%= @room.price %>
                  $('#reservation_days').text(days);
                  $('#reservation_sum').text(total);
                  $('#reservation_total').val(total);
                }

              }
            });

          }
        });

      }
    });

  });
</script>

app/views/reservations/your_reservations.html.erb
<div class="row">
    <div class="col-md-3">
        <ul class="sidebar-list">
            <li class="sidebar-item"><%= link_to "Mes annonces", rooms_path, class:"sidebar-link" %></li>
            <li class="sidebar-item"><%= link_to "Mes réservations", your_reservations_path, class:"sidebar-link active" %></li>
            <li class="sidebar-item"><%= link_to "Mes voyages", your_trips_path, class:"sidebar-link" %></li>
        </ul>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading"> Mes réservations</div>
            <div class="panel-body">
                <% @rooms.each do |room| %>
                <% room.reservations.order("id DESC").each do |reservation| %>
                <div class="row">
                   <div class="col-md-2">
                       Du <%= reservation.start_date.strftime('%d.%m.%y') %> au <%= reservation.end_date.strftime('%d.%m.%y') %>
                   </div>
                   <div class="col-md-6">
                       <%= link_to room_path(reservation.room) do %>
                           <%= image_tag reservation.room.photos[0].image.url(:thumb) if reservation.room.photos.length > 0 %>
                       <% end %>
                   </div>
                   <div class="col-md-2">
                       <%= link_to user_path(reservation.user) do %>
                           <%= image_tag avatar_url(reservation.user), class:"img-circle avatar-medium" %>
                       <% end %>
                   </div>
                   <div class="col-md-2 right">
                       <h4><%= reservation.total %> €</h4>
                   </div>
                </div>
                <hr>
                <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/reservations/your_trips.html.erb
<div class="row">
    <div class="col-md-3">
        <ul class="sidebar-list">
            <li class="sidebar-item"><%= link_to "Mes annonces", rooms_path, class:"sidebar-link" %></li>
            <li class="sidebar-item"><%= link_to "Mes réservations", rooms_path, class:"sidebar-link" %></li>
            <li class="sidebar-item"><%= link_to "Mes voyages", your_trips_path, class:"sidebar-link active" %></li>
        </ul>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading"> Mes voyages</div>
            <div class="panel-body">
                <% @trips.order("id DESC").each do |trip| %>
                <div class="row">
                   <div class="col-md-2">
                       Du <%= trip.start_date.strftime('%d.%m.%y') %> au <%= trip.end_date.strftime('%d.%m.%y') %>
                   </div>
                   <div class="col-md-6">
                       <%= link_to room_path(trip.room) do %>
                           <%= image_tag trip.room.photos[0].image.url(:thumb) if trip.room.photos.length > 0 %>
                       <% end %>
                   </div>
                   <div class="col-md-2">
                       <%= link_to user_path(trip.room.user) do %>
                           <%= image_tag avatar_url(trip.room.user), class:"img-circle avatar-medium" %>
                       <% end %>
                   </div>
                   <div class="col-md-2 right">
                       <h4><%= trip.total %> €</h4>
                   </div>
                </div>
                <hr>
                <% end %>
            </div>
        </div>
    </div>
</div>