config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users,
              :path => '', 
              :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
              :controllers => {:registrations => 'registrations' }
  

  root 'pages#home'
  
  resources :users, only: [:show]
  
  resources :rooms do
    resources :reservations, only: [:create]
  end
  resources :photos

  
  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'
  
  get '/your_trips' => 'reservations#your_trips'
  
  get '/your_reservations' => 'reservations#your_reservations' 

end

app/views/layouts/_navigation.html.erb
<!-- partial navigation -->

<nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" 
data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'FullRoom', root_path, { :class=>"navbar-brand" } %>
        </div>
        <div id="navbar" class="navbar-collapse collapse right">
          <ul class="nav navbar-nav navbar-right">
            
            <!-- ajout d'un logo pour Devenez hôte avec un lien vers la page création de room -->
            <li>
             <%= link_to new_room_path do %>
             <i class="fa fa-home fa-lg"></i> Devenez hôte
             <% end %>
            </li>
             
            <% if (!user_signed_in?) %>
                <li><%= link_to 'Inscription', new_user_registration_path %></li>
                <li><%= link_to 'Connexion', new_user_session_path %></li>
                
            <% else %>
            
                <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
              aria-haspopup="true" aria-expanded="false">
                <!-- affichage avec image tag de l'avatar du current user -->
                <%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %>
                <%= current_user.fullname %>
              <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Mes voyages", root_path %></li>
                <li><%= link_to 'Modifier mon profil', edit_user_registration_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Déconnexion', destroy_user_session_path, 
method: :delete %></li>
              </ul>
            </li>
            <% end %>
            
          </ul>
        </div><!--/.nav-collapse -->
      </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FullRoom</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- lien vers le CSS de datepicker : https://jqueryui.com/datepicker/ -->
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
  <!-- permet de mettre le site en responsive, prend la largeur du device, scale 1 -->
  <meta name="viewport" content="width=device-width, initial-scale=1"> 
  
  <!-- nav bar -->
  <%= render 'layouts/navigation' %>
  <!-- permet d'afficher des messages lorsqu'on met à jour devise -->
<!-- on a enlevé notice et alert ici pour le remplacer par le partial de toastr
  <p class="notice">%= notice %</p>
  <p class="alert">%= alert%</p> 
  -->
<!-- le partial dans le dossier shared dans views qui permet l'affichage de notifications avec toastr -->
<%= render 'shared/message' %>
<div class="container"><%= yield %></div>

</body>
</html>